@startuml

title Workflow - Overview

rectangle "patient controlled" {
actor pat as "patient"
component ui as "UI running in web browser"
}

rectangle "laboratory controlled" {
actor labor as "laboratory assistant"
component excel as "excel sheet"
}

rectangle "COVID-report controlled" {
component cr as "COVID-REPORT"
}

pat --> labor : registration (standing data, contact details)
labor -left-> pat: sample id
labor -> labor : test sample
labor --> excel : test result,\n sample id,\n birthday,\n name \n contact details
excel -> excel : hash (sample id,\n birthday,\n name)
excel --> cr : transfer: test result\n + hash\n + contact details (optional)

cr -> pat: automatic \n notification \n for negative \n test results
pat --> ui: sample id,\n birthday,\n name
ui --> ui : hash (sample id,\n birthday,\n name)
ui --> cr: request test result via hash

note bottom
COVID-Report does only know and store hash and test result

Contact details are only used to send SMS or e-mail.
end note

@enduml